### PR TITLE
Adding Slither to CI

### PR DESCRIPTION
**Pull request by pedrommaiaa**
WIP #20

Slither and a Github code scanning integration were added to `ci.yml`.

Slither is currently failing with error:`ERROR:CryticCompile:Solidity version not found: No solc version set.`

### CODE REVIEW

**Comment by pedrommaiaa** [comment]
Apparently `slither-action@v0.1.1` doesn't work with Foundry, will change to `slither-action@main`, as described [here](https://github.com/crytic/slither-action/issues/11).

**Comment by pedrommaiaa** [comment]
Slither now returns the following: `crytic_compile.platform.exceptions.InvalidCompilation: Could not find the cache/solidity-files-cache.json file.If you are using 'cache = true' in foundry's config file, please remove it.`

cache is already set to `false` in `foundry.toml`, will be investigating the issue.

**Comment by zerosnacks** [comment]
@pedrommaiaa thanks for looking into this!

**Comment by zerosnacks** [comment]
I noticed Foundry is planning to integrate it in their template, could be a good reference: https://github.com/foundry-rs/forge-template/pull/49

**Comment by pedrommaiaa** [comment]
Let's keep an eye on both PRs, should work after they are both solved/merged.

**Pull request merged**
